<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPINHYDW0832" failures="10" tests="108" name="com.epam.testng.CalculatorTest" time="0.037" errors="0" timestamp="2023-04-03T18:14:47 IST" skipped="0">
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDiv" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.002"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySin" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySqrt" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyTg" time="0.001">
    <failure message="expected [-6.4053311966462765] but found [1.0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [-6.4053311966462765] but found [1.0]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEquals(Assert.java:727)
at org.testng.Assert.assertEquals(Assert.java:774)
at com.epam.testng.CalculatorTest.verifyTg(CalculatorTest.java:90)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.epam.testng.CustomTestRunner.main(CustomTestRunner.java:23)
]]>
    </failure>
  </testcase> <!-- verifyTg -->
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySin" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDivForException" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyPow" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDiv" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyIsPositive" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyCtg" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyIsPositive" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDiv" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyCtg" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyPow" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyTg" time="0.000">
    <failure message="expected [0.0] but found [NaN]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [0.0] but found [NaN]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEquals(Assert.java:727)
at org.testng.Assert.assertEquals(Assert.java:774)
at com.epam.testng.CalculatorTest.verifyTg(CalculatorTest.java:90)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.epam.testng.CustomTestRunner.main(CustomTestRunner.java:23)
]]>
    </failure>
  </testcase> <!-- verifyTg -->
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySqrt" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyTg" time="0.000">
    <failure message="expected [0.6484464631832304] but found [1.0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [0.6484464631832304] but found [1.0]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEquals(Assert.java:727)
at org.testng.Assert.assertEquals(Assert.java:774)
at com.epam.testng.CalculatorTest.verifyTg(CalculatorTest.java:90)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.epam.testng.CustomTestRunner.main(CustomTestRunner.java:23)
]]>
    </failure>
  </testcase> <!-- verifyTg -->
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyPow" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyPow" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyIsPositive" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySqrt" time="0.001"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDiv" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyCos" time="0.014">
    <failure message="expected [0.15425144988758405] but found [-0.9880316240928618]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [0.15425144988758405] but found [-0.9880316240928618]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEquals(Assert.java:727)
at org.testng.Assert.assertEquals(Assert.java:774)
at com.epam.testng.CalculatorTest.verifyCos(CalculatorTest.java:102)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.epam.testng.CustomTestRunner.main(CustomTestRunner.java:23)
]]>
    </failure>
  </testcase> <!-- verifyCos -->
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyCos" time="0.001">
    <failure message="expected [1.0] but found [0.0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [1.0] but found [0.0]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEquals(Assert.java:727)
at org.testng.Assert.assertEquals(Assert.java:774)
at com.epam.testng.CalculatorTest.verifyCos(CalculatorTest.java:102)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.epam.testng.CustomTestRunner.main(CustomTestRunner.java:23)
]]>
    </failure>
  </testcase> <!-- verifyCos -->
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.001"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDivForException" time="0.001"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySin" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyIsNegative" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyPow" time="0.001"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDiv" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDiv" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyIsNegative" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDiv" time="0.003"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDiv" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyCos" time="0.000">
    <failure message="expected [-0.8390387292223656] but found [-0.5440716964379951]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [-0.8390387292223656] but found [-0.5440716964379951]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEquals(Assert.java:727)
at org.testng.Assert.assertEquals(Assert.java:774)
at com.epam.testng.CalculatorTest.verifyCos(CalculatorTest.java:102)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.epam.testng.CustomTestRunner.main(CustomTestRunner.java:23)
]]>
    </failure>
  </testcase> <!-- verifyCos -->
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyCtg" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyTg" time="0.001">
    <failure message="expected [-1.6197751905438615] but found [1.0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [-1.6197751905438615] but found [1.0]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEquals(Assert.java:727)
at org.testng.Assert.assertEquals(Assert.java:774)
at com.epam.testng.CalculatorTest.verifyTg(CalculatorTest.java:90)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.epam.testng.CustomTestRunner.main(CustomTestRunner.java:23)
]]>
    </failure>
  </testcase> <!-- verifyTg -->
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.001"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySin" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySqrt" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyIsNegative" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyCos" time="0.000">
    <failure message="expected [0.5624787751985085] but found [0.8268117243068012]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [0.5624787751985085] but found [0.8268117243068012]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEquals(Assert.java:727)
at org.testng.Assert.assertEquals(Assert.java:774)
at com.epam.testng.CalculatorTest.verifyCos(CalculatorTest.java:102)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.epam.testng.CustomTestRunner.main(CustomTestRunner.java:23)
]]>
    </failure>
  </testcase> <!-- verifyCos -->
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySin" time="0.001"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDivForException" time="0.001"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyCtg" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDivForException" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyPow" time="0.001"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyIsNegative" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyCos" time="0.000">
    <failure message="expected [0.5253219888177297] but found [-0.8509035245341184]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [0.5253219888177297] but found [-0.8509035245341184]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEquals(Assert.java:727)
at org.testng.Assert.assertEquals(Assert.java:774)
at com.epam.testng.CalculatorTest.verifyCos(CalculatorTest.java:102)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.epam.testng.CustomTestRunner.main(CustomTestRunner.java:23)
]]>
    </failure>
  </testcase> <!-- verifyCos -->
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyCtg" time="0.002"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySqrt" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDiv" time="0.003"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDiv" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDiv" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyMult" time="0.001"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyTg" time="0.000">
    <failure message="expected [1.4699429752082733] but found [1.0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [1.4699429752082733] but found [1.0]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEquals(Assert.java:727)
at org.testng.Assert.assertEquals(Assert.java:774)
at com.epam.testng.CalculatorTest.verifyTg(CalculatorTest.java:90)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.epam.testng.CustomTestRunner.main(CustomTestRunner.java:23)
]]>
    </failure>
  </testcase> <!-- verifyTg -->
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyIsPositive" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyPow" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySub" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDiv" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyIsPositive" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyDiv" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyPow" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifySum" time="0.000"/>
  <system-out/>
  <testcase classname="com.epam.testng.CalculatorTest" name="verifyIsNegative" time="0.001"/>
  <system-out/>
</testsuite> <!-- com.epam.testng.CalculatorTest -->
